apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blitzmonk-cert-tls
  namespace: blitzmonk
spec:
  secretName: blitzmonk-secret
  issuerRef:
    name: le-issuer
    kind: ClusterIssuer
  dnsNames:
    - bm.ghulammuzz.com