---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexmaster-deployment
  labels:
    app: flexmaster-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flexmaster-app
      version: v1
  template:
    metadata:
      labels:
        app: flexmaster-app
        version: v1
    spec:
      containers:
      - name: flexmaster
        image: ghulammuzz/flexmaster:456dc61
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"    
          limits:
            memory: "256Mi"
            cpu: "1"     
        envFrom:
        - configMapRef:
            name: flexmaster-env
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: dockerkey
