apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flexmaster-chart.fullname" . }}
  labels:
    app: {{ include "flexmaster-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "flexmaster-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flexmaster-chart.name" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "flexmaster-chart.name" . }}
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flexmaster
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.env.APP_PORT }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.env.APP_PORT }}
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: {{ include "flexmaster-chart.fullname" . }}-env
        ports:
        - containerPort: {{ .Values.env.APP_PORT | int }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ .name }}
{{- end }}
{{- end }}
